<a href="https://colab.research.google.com/github/AugustoLorenzoGassos/Universidad_anahuac_fullstack_modulo1_desarrollo_python/blob/main/Anahuac_Semana2D%C3%ADa2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Módulos y librerias

Libreria - Conjuno de funcionalidades para llevar a cabo tareas

Módulos - Scripts dentro de librerias

In [ ]:
import math
math.exp(1e-5)
math.exp(1e-5)-1
math.expm1(1e-5)



1.0000050000166668e-05

In [ ]:
from fractions import Fraction
Fraction(16,-10)

Fraction(-8, 5)

In [ ]:
import random as Rnd

Rnd.random()
Rnd.uniform(2.5,10)

5.116925725506804

In [ ]:
#ndarrays
#pip install numpy

import numpy as np

Lista = [6,8,10,12]
Arreglo = np.array(Lista)

print(Lista)
print(Arreglo)
print(Arreglo - 2)
print(Arreglo * Arreglo, "\n\n")

[6, 8, 10, 12]
[ 6  8 10 12]
[ 4  6  8 10]
[ 36  64 100 144] 




In [ ]:
MiVector = np.array(['este','es','un','vector'])
print(MiVector)

MiMatriz = [[1,2,3],[4,5,6],[7,8,9]]
MiMatrizA = np.array(MiMatriz)
print(MiMatrizA)

['este' 'es' 'un' 'vector']
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
MiMatrizA.dtype
MiVector.dtype

dtype('<U6')

In [ ]:
arr1 = np.array([np.arange(0,5),np.arange(0,5)*5])
arr1.shape

(2, 5)

In [ ]:
#print(MiVector[-2])
#print(MiMatriz[-2])

print(MiVector[0:3])
print(MiVector[3:])


['este' 'es' 'un']
['vector']


In [ ]:
import pandas as pnd

Datos = np.array(['g','e','e','k','m'])
Serie = pnd.Series(Datos, index=[1,2,3,4,5])

print(Serie)

1    g
2    e
3    e
4    k
5    m
dtype: object


In [ ]:
dic = {
    'manzanas':10,
    'peras':20,
    'chayotes':30,
    'uvas':40}

SerieD = pnd.Series(dic)
print(SerieD)

manzanas    10
peras       20
chayotes    30
uvas        40
dtype: int64


In [ ]:
Serie[1:3]

,0
2,e
3,e


In [ ]:
Datos = [[10,11,12,13],
         [20,21,22,23],
         [30,31,32,33]]

Columnas = ['C1','C2','C3','C4']
Filas = ['F1','F2','F3']

Frame = pnd.DataFrame(Datos, columns=Columnas, index=Filas)

print(Frame)


    C1  C2  C3  C4
F1  10  11  12  13
F2  20  21  22  23
F3  30  31  32  33


In [ ]:
Dic = {
    'Nombre':['Juan','Laura','Pepe'],
    'Edad':[42,40,37],
    'Departamento':['Biología','Química','Geologóia']
}

FrameDic = pnd.DataFrame(Dic)

print(FrameDic)

  Nombre  Edad Departamento
0   Juan    42     Biología
1  Laura    40      Química
2   Pepe    37    Geologóia


In [ ]:
Frame.to_csv('FrameCSV')

NewFrame = pnd.read_csv('FrameCSV', index_col=0)
#print(NewFrame)
print(Frame['C1'][0])



#print(Frame.head(2))
#print(Frame.tail(2))

10


/tmp/ipython-input-323/1583006763.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(Frame['C1'][0])
